### ISSUE TITLE
The version of some Winget apps fails to load and is shown as "Unknown" on the infobox section

### ISSUE THREAD

**Issue by martinet101** [martinet101/WingetUI#307]

**Comment by ppvnf** [comment]
It seems like you forgot to add tags to this issue

**Comment by martinet101** [comment]
True!

**Comment by martinet101** [comment]
I'm sorry. i forgot about that. Please note that a few days ago I improved the discover software parser, so this could be fixed already (i couldn't reproduce this issue).
Could you please test that agaon?

**Comment by ppvnf** [comment]
> I'm sorry. i forgot about that. Please note that a few days ago I improved the discover software parser, so this could be fixed already (i couldn't reproduce this issue). Could you please test that agaon?

Maybe it happens only on Windows 10?

It's not fixed for me yet:

[Videos.zip](https://github.com/martinet101/WingetUI/files/9893542/Videos.zip)

**Comment by ppvnf** [comment]
By the way, this problem happens on clean Windows 10 installations

**Comment by ppvnf** [comment]
This problem actually seems to have gotten worse...

**Comment by martinet101** [comment]
Could you please send a screenshot of the failing packages?

**Comment by ppvnf** [comment]
> Could you please send a screenshot of the failing packages?

It doesn't happen with any specific package (it seems random)
 
https://user-images.githubusercontent.com/73800734/200680619-5225c0c9-89ff-4f2c-a878-42ad72310f6f.mp4

**Comment by ppvnf** [comment]
Couldn't this be solved by making the `winget show` request wait a little bit more for results or retrying if there's an unknown field?

**Comment by martinet101** [comment]
I don't think so, because looking at the outputs the packages are actually shown by winget, but they are just not parsed correctly by WingetUI.

My bet is that what is failing is the wingetui cli parser

**Comment by martinet101** [comment]
Fixed!

The issue is actually caused by winget itself, but looping the command until it returns a valid output fixes the issue for 99.756% of the times this happen

**Comment by ppvnf** [comment]
> returns a valid output fixes the issue for 99.756% of the times this happen

Thanks a lot! Lol, nice statistics by the way!

**Comment by ppvnf** [comment]
I've tested the latest head and it seems better. But I am still facing the following problems sometimes. 

1. no info is diplayed (rare):

![Captura de tela 2022-12-07 215708](https://user-images.githubusercontent.com/73800734/206330193-c1188851-a16e-4f5b-9542-bd444b4d4426.png)
![Captura de tela 2022-12-07 215835](https://user-images.githubusercontent.com/73800734/206330195-caa42287-5699-4149-8d6d-8fd03d350e67.png)

2. version is not shown:

![Captura de tela 2022-12-07 220131](https://user-images.githubusercontent.com/73800734/206330637-fccd6132-7e31-4de3-94f5-03b2a8b69ca1.png)
![Captura de tela 2022-12-07 220213](https://user-images.githubusercontent.com/73800734/206330638-f06a8dfa-7e17-49f6-b9a4-0f18f6c6c098.png)

Python CLI shows the version, but WingetUI doesn't

**Comment by martinet101** [comment]
Fixed using the same method, brutte-force run the command until it returns something

**Comment by ppvnf** [comment]
Now version loads fine, but other fields are unknown (the opposite of what happened before https://github.com/martinet101/WingetUI/commit/85ae7abc5cc82d884d60c1eff4ff99dad8e72765). Thank you nonetheless

![Captura de tela 2022-12-17 013754](https://user-images.githubusercontent.com/73800734/208225321-f0a2f8c8-d6f3-4a3b-9066-5c79abf0f516.png)

**Comment by martinet101** [comment]
does this happen again with the same frequency as before?


Because for me it is still fixed...


Anyway, I have done what I could,lets hope that winget 1.4 fixes that

**Comment by ppvnf** [comment]
It happens quite often. I've tested it on both Windows 10 and 11, but I am glad I can now see the version! Anyway, hopefully MS improves Winget reliability. Or maybe json parsing could help

**Comment by martinet101** [comment]
> Or maybe json parsing could help

I'm looking into it, but I need winget.run to release its api.

**Comment by ppvnf** [comment]
I did a simple test to see if it is possible to display Winget/Scoop manifests in PShell. I don't now if this is what you are looking for:

Winget:
1 - `Install-Module PowerShell-yaml`
2 - `Invoke-WebRequest -Uri "https://raw.githubusercontent.com/microsoft/winget-pkgs/master/manifests/e/Eziriz/DotNetReactor/6.8.0.0/Eziriz.DotNetReactor.locale.en-US.yaml" | ConvertFrom-Yaml`

Result:

![Captura de tela 2022-12-18 202840](https://user-images.githubusercontent.com/73800734/208325109-905840f8-4b4b-40cc-a09a-60d24d1c0a98.png)

Scoop:
1 - `Get-Content C:\Users\<user>\scoop\buckets\games\bucket\0ad.json | ConvertFrom-Json`

Result:

![Captura de tela 2022-12-18 202822](https://user-images.githubusercontent.com/73800734/208325108-5c6537af-49d6-4b81-8083-439d6e04e40b.png)

**Comment by martinet101** [comment]
the issue here is not reading, but getting the manifest file.

For scoop, some of the meta is actually read from the json, but the issue happens with winget only.

I'll further investigate this, since maybe the manifest cna be parsed from the URL.

**Comment by ppvnf** [comment]
Thanks for trying it. Should this be reopen or do you think this is the same discussion of https://github.com/martinet101/WingetUI/issues/223? 

I am not sure how to find scoop manifests consistently. You could find most of them using (https://raw.githubusercontent.com/ScoopInstaller/ **Bucket Name** /master/bucket/ **Manifest Name** .json). However, if the bucket isn't official, i.e. not inside ScoopInstaller that wouldn't work. I am not sure it's worth it though.

As for Winget, I believe you implemented a way to finding manifest in https://github.com/martinet101/WingetUI/commit/315a4887843bd0e7ce6454ab82f5507428a38487

**Comment by ppvnf** [comment]
1 - What I find strange about this bug is the fact that the console also doesn't show the missing info:

<details>

![Captura de tela 2022-12-19 091639](https://user-images.githubusercontent.com/73800734/208426507-d2b39960-177a-45f8-b8bd-e7dc92bc123c.png)
![Captura de tela 2022-12-19 091701](https://user-images.githubusercontent.com/73800734/208426512-0f2ad27f-bc47-4e21-ae30-2def5df3c1dd.png)
</details>

2 - There's also a more rare bug (like 1 in 15 packages) where nothing is displayed:

<details>

![Captura de tela 2022-12-19 091529](https://user-images.githubusercontent.com/73800734/208426720-967e9fbf-1ecc-4d5e-b4cf-7df124527182.png)
![Captura de tela 2022-12-19 091519](https://user-images.githubusercontent.com/73800734/208426725-d54cbbbe-134f-4f29-bcb4-ad8f58c9411e.png)
</details>

**Comment by martinet101** [comment]
the second one should be my fault. this one should be fixable.

the first one, is the same issue as always

**Comment by ppvnf** [comment]
Probably a stupid idea, but how about having an option to load screenshots after the package info to solve the first issue of https://github.com/marticliment/WingetUI/issues/307#issuecomment-1357604272? I thought about this because this problem started after the screenshot update, but maybe it's not related at all

**Comment by marticliment** [comment]
Honestly, I don't think this is an issue related to the changes to screenshots. The code is completely separated and one uses winget and the other parses an online json file, so I don't think they are related.
If you want, you can test older versions (1.0-1.2) to see if they work correctly, but i don't think they will

**Comment by ppvnf** [comment]
I've just tested it. WingetUI-1.4.2 (the last version before screenshot) doesn't have this bug for some reason. If it's not the screenshot I have no idea what could be the cause of this issue

**Comment by marticliment** [comment]
Well, this is suspicious, since the bundled winget version did not change...

**Comment by marticliment** [comment]
Please note that some wording changes could have been done v1.4, i will analyze every parameter to see if it has changed its name.

**Comment by ppvnf** [comment]
I think the reasons for the different logs above isn't Winget 1.4. I've tried using Winget 1.3 with Python 3.11 (I was using 3.10 before) and I believe the logs are clear now about what is happening:

![Captura de tela 2023-01-05 233552](https://user-images.githubusercontent.com/73800734/211009112-45e6d546-70cc-4c40-b4c3-5b7b87afa4c2.png)
![Captura de tela 2023-01-05 233841](https://user-images.githubusercontent.com/73800734/211009103-5093477a-0b48-4268-9fa8-a85e5bbc58c8.png)
![Captura de tela 2023-01-05 233610](https://user-images.githubusercontent.com/73800734/211009109-a790e88f-1f92-4021-aa08-3a7fcdc5c45e.png)

**Comment by marticliment** [comment]
Winget is (in theory) about to release a COM API, so this part of winget could work with the api, preventing this issue to happen

**Comment by ioqy** [comment]
I have the same issue, but in my case the package id gets truncated or rather the truncated package id from the UI is used. The UI shows the package id as `Microsoft.DotNet.Framework.Develop…` and this is also what is used when winget gets queried.

While trying to reproduce this issue I also had the case that it sometimes the package id is not truncated and everything is working properly and the infobox is able to load.

Winget log from `%TEMP%\WinGet\defaultState\WinGet-2023-02-06-09-58-57.438.log`:

<details>

```
2023-02-06 09:58:57.439 [CORE] WinGet, version [1.4.10173], activity [{D408F208-D25E-448C-AA75-648ADAE41E94}]
2023-02-06 09:58:57.440 [CORE] OS: Windows.Desktop v10.0.19045.2486
2023-02-06 09:58:57.440 [CORE] Command line Args: C:\Users\Admin\AppData\Local\Programs\WingetUI\winget-cli\winget.exe  show --id Microsoft.DotNet.Framework.Develop… -e --versions --source winget --accept-source-agreements
2023-02-06 09:58:57.440 [CORE] IsCOMCall:0; Caller: winget-cli
2023-02-06 09:58:57.441 [CLI ] WinGet invoked with arguments: 'show' '--id' 'Microsoft.DotNet.Framework.Develop…' '-e' '--versions' '--source' 'winget' '--accept-source-agreements'
2023-02-06 09:58:57.441 [CLI ] Found subcommand: show
2023-02-06 09:58:57.441 [CLI ] Leaf command to execute: root:show
2023-02-06 09:58:57.441 [CLI ] Executing command: show
2023-02-06 09:58:57.444 [REPO] Named source requested, found: winget
2023-02-06 09:58:57.445 [CORE] Started trust validation of msix at: C:\Users\Admin\AppData\Local\Microsoft/WinGet\State\defaultState\Microsoft.PreIndexed.Package\Microsoft.Winget.Source_8wekyb3d8bbwe\source.msix
2023-02-06 09:58:57.491 [CORE] Result for certificate chain validation of Microsoft origin: 0
2023-02-06 09:58:57.521 [CORE] Result for trust info validation of the msix: 0
2023-02-06 09:58:57.877 [REPO] Opening SQLite Index for ImmutableRead at 'C:\Users\Admin\AppData\Local\Temp\WinGet\defaultState\{08A3FD1E-2FC0-4809-9DFC-6E98B195C7EC}'
2023-02-06 09:58:57.878 [SQL ] Opening SQLite connection #1: 'C:\Users\Admin\AppData\Local\Temp\WinGet\defaultState\{08A3FD1E-2FC0-4809-9DFC-6E98B195C7EC}' [1, 40]
2023-02-06 09:58:57.882 [REPO] Opened SQLite Index with version [1.6], last write [2023-02-03 22:37:41.000]
2023-02-06 09:58:57.928 [CLI ] No app found matching input criteria
2023-02-06 09:58:57.932 [CLI ] Terminating context: 0x8a150014 at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\WorkflowBase.cpp:337
```

</details>

WingetUI log:

<details>

```
C:\Users\Admin\AppData\Local\Programs\WingetUI\sudo\gsudo.exe
C:\Users\Admin\AppData\Local\Programs\WingetUI\sudo
🟢 checkQueue Thread started!
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.0030007362365722656 to load all language files
🔵 Language file up-to-date
🔵 Starting main application...
Scanning for instances...
Found lock file(s), reactivating...
🔵 Starting update check
🟢 Downloaded latest metadata to local file
🔵 Loaded metadata from local file
b'v1.4.10173\r\n'
None
updating winget
🔵 Version URL: https://versions.marticliment.com/versions/wingetui.ver
🟢 Updates not found
b'1.2.1\r\n'
None
Reactivation signal ignored: RaiseWindow_[1675673777.5972126]
{'wingetFound': True, 'scoopFound': False, 'chocoFound': True, 'sudoFound': True, 'wingetVersion': 'v1.4.10173\r', 'scoopVersion': 'Scoop is disabled', 'chocoVersion': '1.2.1\r', 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r'}
Reached main ui load milestone
🔵 Is Dark
🟢 Starting winget search, winget on C:\Users\Admin\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
🟢 Discover tab loaded
🟢 Starting winget search, winget on C:\Users\Admin\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
🟢 Starting choco search, choco on choco.exe...
🟢 Upgrades tab loaded
🟢 Starting winget search, winget on C:\Users\Admin\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
🟢 Starting choco search, choco on choco.exe...
🟢 Discover tab loaded
🟢 Settings tab loaded!
🟢 About tab loaded!
🟢 Main application loaded...
Win32Mica Error: win32 version 19045 is not supported
🟢 Chocolatey uninstallable packages search finished
🟢 Searching for string ""
Name                                 Id                         Version Available
🟢 Winget search finished
🟢 Searching for string ""
🟢 Winget uninstallable packages search finished
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 120
🟢 Chocolatey search finished
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 3
None
🟢 Winget search finished
🟢 Total packages: 11313
🟠 Icon Microsoft.DotNet.Framework.Develop… not found in json
🟠 Icon Microsoft.DotNet.Framework.Develop… not found in json
🟢 Starting winget search, winget on C:\Users\Admin\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Starting get info for id Microsoft.DotNet.Framework.Develop…
🟢 Loading versions for Microsoft.DotNet.Framework.Develop…
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
['C:\\Users\\Admin\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Microsoft.DotNet.Framework.Develop…', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
🔵 Copying log to the clipboard...

```

</details>

**Comment by marticliment** [comment]
This is a different issue, and it resulted to be winget's fault. The winget client often chops long names/IDs. There's an issue somewhere talking about this, but in a summary, we need winget to fix this

**Comment by ppvnf** [comment]
> Winget is (in theory) about to release a COM API, so this part of winget could work with the api, preventing this issue to happen

Nice!

**Comment by ppvnf** [comment]
<img width="206" alt="Screenshot 2023-03-02 143542" src="https://user-images.githubusercontent.com/73800734/222553151-9320c662-87ed-4db3-8813-83cec54ba6e8.png">
as of 1.6.2 this is the only field that is not showing properly

**Comment by marticliment** [comment]
On winget, i assume?

**Comment by ppvnf** [comment]
yes

**Comment by marticliment** [comment]
Could you please open a new issue?

**Comment by ppvnf** [comment]
this issue has been mostly fixed. However rarely a few packages like Microsoft.DotNet.Framework.DeveloperPack_4 (the only one that I can remember) are not able to be loaded. They keep trying to find the info for a long time and then show it is unavailable:
<img width="530" alt="Screenshot 2023-04-16 095332" src="https://user-images.githubusercontent.com/73800734/232283365-89fedef2-059c-4d7c-a919-3a857f8e60e4.png">
<img width="536" alt="Screenshot 2023-04-16 095657" src="https://user-images.githubusercontent.com/73800734/232283493-488b83d8-b022-484b-b8e4-75ada006cf8b.png">

**Comment by marticliment** [comment]
all right then
