### ISSUE TITLE
[BUG/ISSUE] (beta) stripes when hovering packages without screenshots

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#346]
## Before submitting the issue

- [X] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [X] **I have checked that I am running the latest version of WingetUI**
- [X] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [X] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**

</b>

## Expected behaviour

When hovering the info menu, if there aren't screenshots available, these dark lines will appear under the cursor (only in the screenshot area):

## Screenshots

![Captura de tela 2022-10-28 180519](https://user-images.githubusercontent.com/73800734/198741715-9f7550e4-e730-4aea-8a1d-4247a39fad94.png)

**Comment by martinet101** [comment]
Fixed!

**Comment by ppvnf** [comment]
> Fixed!

Not fully fixed: 

![Captura de tela 2022-10-29 104020](https://user-images.githubusercontent.com/73800734/198834786-52f6079f-015c-40f0-8d16-3739ec92f296.png)

There are still a few stripes left

**Comment by martinet101** [comment]
Which package are you using?

**Comment by ppvnf** [comment]
It's fixed now! thanks!
